### ISSUE TITLE
🐛 [Bug]: 

### ISSUE THREAD

**Issue by 75910456** [DevCloudFE/ng-devui#315]
### Version

13.3.0

### Angular Version

12.2.18

### Link to minimal reproduction

d-select 报错

### Step to reproduce

 <d-select #select1="select"  [filterKey]="'name'" [(ngModel)]="currentOption1"
            [isSearch]="true" (toggleChange)="toggleChange1($event)">
        </d-select>

  @ViewChild('select', { static: true }) selectComponent1: SelectComponent;
 toggleChange1($event) {
    if ($event) {
      this.selectComponent1.**loadStart**();
    }
  }

loadStart报错如下：

core.js:7744 ERROR TypeError: componentFactory.create is not a function
    at ViewContainerRef.createComponent (core.js:23278:1)
    at LoadingDirective.createLoadingBackdrop (ng-devui-loading.mjs:213:39)
    at LoadingDirective.startLoading (ng-devui-loading.mjs:177:18)
    at LoadingDirective.showLoadingChangeEvent (ng-devui-loading.mjs:168:18)
    at LoadingDirective.ngOnChanges (ng-devui-loading.mjs:130:22)
    at LoadingDirective.rememberChangeHistoryAndInvokeOnChangesHook (core.js:1511:1)
    at callHook (core.js:2549:1)
    at callHooks (core.js:2508:1)
    at executeCheckHooks (core.js:2440:1)
    at selectIndexInternal (core.js:8547:1)

**Comment by Simplelegant** [comment]
你好，升级到最新版本试下呢

**Comment by kwongtn** [comment]
@75910456 angular 和 devui 版本必须匹配，比如 DevUI 13 需匹配 angular 13
